import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { StoreProvider } from './store/StoreProvider'
import NavBar from './components/NavBar/NavBar'
import AuthProvider from './components/AuthProvider/AuthProvider'
import SnowWrapper from './components/Snow/SnowWrapper'
import Script from 'next/script'

const sfPro = localFont({
	src: [
		{
			path: '../public/fonts/SF-Pro-Display-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/SF-Pro-Display-Medium.otf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../public/fonts/SF-Pro-Display-Semibold.otf',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../public/fonts/SF-Pro-Display-Bold.otf',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-sf-pro',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='dark'>
			<head>
				<Script
					src='https://telegram.org/js/telegram-web-app.js'
					strategy='beforeInteractive'
				/>
			</head>
			<body className={`${sfPro.variable} antialiased`}>
				<StoreProvider>
					<AuthProvider>{children}</AuthProvider>
					<NavBar />
					<SnowWrapper />
				</StoreProvider>
			</body>
		</html>
	)
}
